site_name: SIP Framework Documentation
site_description: 'Documentation for using & developing with the SIP Framework'
site_author: 'IKOR'
repo_url: 'https://github.com/IKOR-GmbH/sip-framework'
edit_uri: 'edit/main/docs/'
copyright:  © Copyright 2021, <a href="https://ikor.one">IKOR GmbH</a> & contributors

nav:
    - Introduction: README.md
    - Installation Guide: installation.md
    - Archetype: archetype.md
    - Core: core.md
    - Declarative Structure: declarative.md
    - Integration Starter: integration-starter.md
    - Starter Parent: starter-parent.md
    - Security: security.md
    - Test Kit: test-kit.md
    - Middle Component: middle-component.md
    - Framework Version Upgrade: framework_version_upgrade.md
    - License: license.md
    - Contribution Guidelines: CONTRIBUTING.md
    - Code Of Conduct: CODE_OF_CONDUCT.md
    - Changelog: changelog.md
    - JavaDoc Latest Development: './javadoc/latest/index.html'
    # JAVADOC_RELEASES sed marker, do not delete
    - JavaDoc 3.1.0: './javadoc/3.1.0/index.html'
    - JavaDoc 3.0.0: './javadoc/3.0.0/index.html'
    - JavaDoc 2.4.0: './javadoc/2.4.0/index.html'
    - JavaDoc 2.3.0: './javadoc/2.3.0/index.html'
    - JavaDoc 2.2.0: './javadoc/2.2.0/index.html'
    - JavaDoc 2.1.0: './javadoc/2.1.0/index.html'
    - JavaDoc 2.0.2: './javadoc/2.0.2/index.html'
    - JavaDoc 2.0.0: './javadoc/2.0.0/index.html'
    - JavaDoc 1.0.0: './javadoc/1.0.0/index.html'
    - Find out more about IKOR: 'https://ikor.one/produkt/system-integration-platform'
    - Impressum: 'https://ikor.one/impressum/'

collapse_navigation: false

theme:
  name: 'readthedocs'
  language: 'en'
  include_homepage_in_sidebar: True

docs_dir: 'docs'

extra_css:
    - css/extra.css

extra_javascript:
    - javascript/javadoc_menu_dropdown.js
    - javascript/copy_to_clipboard.js

markdown_extensions:
  - toc:
      permalink: true
  - sane_lists
  - pymdownx.superfences
  - pymdownx.emoji:
      # with the unicode images provided by alt we should be safe regarding
      # license attributions as we are not using pictures from a specific library
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
