site_name: SIP Framework Documentation
site_description: 'Documentation for using & developing with the SIP Framework'
site_author: 'IKOR'
repo_url: 'https://github.com/IKOR-GmbH/sip-framework'
edit_uri: 'edit/main/docs/'
copyright:  © Copyright 2021, <a href="https://www.ikor.de/impressum.html">IKOR GmbH</a> & contributors

nav:
    - Introduction: README.md
    - Installation Guide: installation.md
    - Archetype: archetype.md
    - Core: core.md
    - Middle Component: middle-component.md
    - Integration Starter: integration-starter.md
    - Starter Parent: starter-parent.md
    - Security: security.md
    - License: license.md
    - Contribution Guidelines: CONTRIBUTING.md
    - Code Of Conduct: CODE_OF_CONDUCT.md
    - Changelog: changelog.md
    - JavaDoc of latest Release: './javadoc/latest/index.html'
    - Find out more about IKOR: 'https://ikor.one'

collapse_navigation: false

theme:
  name: 'readthedocs'
  language: 'en'
  include_homepage_in_sidebar: True

docs_dir: 'docs'

extra_css:
    - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - sane_lists
  - pymdownx.superfences
  - pymdownx.emoji:
      # with the unicode images provided by alt we should be safe regarding
      # license attributions as we are not using pictures from a specific library
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
