#set( $dollar = '$' )
spring:
  application:
    name: ${projectName}

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs           #default swagger docs
  swagger-ui:
    url: /adapter/api-docs    #custom swagger docs set as default
    path: /swagger-ui.html

camel:
  rest:
    component: servlet
    binding-mode: json
    data-format-property[prettyPrint]: true
    port: ${dollar}{server.port:8080}
    host: localhost
    context-path: /adapter
    api-context-path: /api-doc
    api-context-route-id: api-docs-route-id
    api-property[api.title]: ${projectName}
    api-property[api.version]: ${version}

# SIP Security configuration
# This configuration represents the template to use for configuring security. If security is not needed, all
# configuration properties below under sip.security can be deleted.
sip.security:
  # Template for SSL configuration. By default SSL is disabled.
  ssl:
    enabled: false # SSL will be enabled by simply setting this value to true

    # These settings have to be set by the application, by default ssl is disabled
    server:
      client-auth: none
      key-store:
      key-store-password:
      key-store-type:
      key-alias:
      key-password:

    # If the adapter requires different setups for outgoing traffic (http client) and server, values for the following
    # client properties should be added. By default, the outgoing traffic properties will fallback to sip.ssl.server configuration.
    client:
      enabled: false
      key-store:
      key-store-password:
      key-store-type:
      key-alias:
      key-password:

  # Template for authentication configuration. For using it uncomment the configuratio and fill in the proper values
#  authentication:
#    disable-csrf:
#    auth-providers:
#      - classname:
#        ignored-endpoints:
#        validation:
#          classname:
#          file-path:

