sip.core:
  translation:
    fileLocations: classpath:translations/translated-messages, classpath:translations/sip-core-messages
    default-encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
    lang: en
  tracing:
    enabled: false
    exchange-formatter:
      showHeaders: true
      showExchangeId: true
    traceType: "*"
  metrics:
    external-endpoint-health-check:
      enabled: true
      scheduler:
        fixed-delay: 900000
        initial-delay: 5000

management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: health,info,metrics,loggers,prometheus,adapter-routes

springdoc:
  show-actuator: true
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
