sip.core:
  translation:
    enabled: true
    fileLocations: classpath:translations/translated-messages
    sipFileLocations:
      - classpath:translations/sip-core-messages
      - classpath:translations/sip-test-kit-messages
      - classpath:translations/sip-security-messages
      - classpath:translations/sip-mc-messages
    default-encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
    lang: en
  tracing:
    enabled: false
    exchange-formatter:
      showHeaders: true
      showExchangeId: true
    log: true
  actuator:
    endpoints: adapter-routes,adapterdefinition,tracing
    adapter-routes:
      enabled: true
    adapterdefinition:
      enabled: true
    extensions:
      info:
        enabled: true
      health:
        enabled: true
  proxy:
    enabled: true
  metrics:
    external-endpoint-health-check:
      enabled: true
      scheduler:
        fixed-delay: 900000
        initial-delay: 5000
  declarativestructure:
    enabled: true
server:
  servlet:
    context-path:
management:
  info:
    camel:
      enabled: false
  endpoints.web.exposure.include: health,info,metrics,loggers,prometheus
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          down: 200

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /adapter/api-docs    #custom swagger docs set as default
    path: /swagger-ui.html
    disable-swagger-default-url: true

#context path for adapter routes
camel:
  servlet:
    mapping:
      context-path: /adapter/*
