blank_issues_enabled: true #set to false if a template has to be chosen
contact_links:
  - name: opensource@ikor.de
    url: opensource@ikor.de
    about: Please report security vulnerabilities here instead of creating an issue.
