#######################################
#
# Default settings for sip-security
#
#######################################

server:
  ssl:
    enabled: ${sip.security.ssl.enabled}
    client-auth: ${sip.security.ssl.server.client-auth}
    key-store: ${sip.security.ssl.server.key-store}
    key-store-password: ${sip.security.ssl.server.key-store-password}
    key-store-type: ${sip.security.ssl.server.key-store-type}
    key-alias: ${sip.security.ssl.server.key-alias}
    key-password: ${sip.security.ssl.server.key-password}

camel:
  ssl.config:
    key-managers:
      key-password: ${sip.security.ssl.client.key-password}
      key-store:
        resource: ${sip.security.ssl.client.key-store}
        password: ${sip.security.ssl.client.key-store-password}
        type: ${sip.security.ssl.client.key-store-type}
    trust-managers.key-store:
      resource: ${sip.security.ssl.client.key-store}
      password: ${sip.security.ssl.client.key-store-password}
      type: ${sip.security.ssl.client.key-store-type}

sip.security:
  ssl:
    enabled: false
    # These settings have to be set by the application, by default ssl is disabled
    server:
      client-auth: none
      key-store:
      key-store-password:
      key-store-type:
      key-alias:
      key-password:

    # Default for these settings are not to set anything, but take what comes out of the box
    # with spring boot, by setting enabled to true, we take the configured values
    client:
      enabled: false
      key-store: ${sip.security.ssl.server.key-store}
      key-store-password: ${sip.security.ssl.server.key-store-password}
      key-store-type: ${sip.security.ssl.server.key-store-type}
      key-alias: ${sip.security.ssl.server.key-alias}
      key-password: ${sip.security.ssl.server.key-password}

# Disabling Springs security autoconfiguration which applies base auth by default if no other authentication is provided.
spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration