package com.example.customerservice;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import java.util.List;

/** This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2 */
@WebService(name = "CustomerService", targetNamespace = "http://customerservice.example.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

  /**
   * @param customer
   */
  @WebMethod
  @Oneway
  @RequestWrapper(
      localName = "updateCustomer",
      targetNamespace = "http://customerservice.example.com/",
      className = "com.example.customerservice.UpdateCustomer")
  public void updateCustomer(@WebParam(name = "customer", targetNamespace = "") Customer customer);

  /**
   * @param name
   * @return returns java.util.List<com.example.customerservice.Customer>
   * @throws NoSuchCustomerException
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
      localName = "getCustomersByName",
      targetNamespace = "http://customerservice.example.com/",
      className = "com.example.customerservice.GetCustomersByName")
  @ResponseWrapper(
      localName = "getCustomersByNameResponse",
      targetNamespace = "http://customerservice.example.com/",
      className = "com.example.customerservice.GetCustomersByNameResponse")
  public List<Customer> getCustomersByName(
      @WebParam(name = "name", targetNamespace = "") String name) throws NoSuchCustomerException;
}
