package com.example.customerservice;

import javax.xml.ws.WebFault;

/** This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2 */
@WebFault(name = "NoSuchCustomer", targetNamespace = "http://customerservice.example.com/")
public class NoSuchCustomerException extends Exception {

  /** Java type that goes as soapenv:Fault detail element. */
  private NoSuchCustomer faultInfo;

  /**
   * @param faultInfo
   * @param message
   */
  public NoSuchCustomerException(String message, NoSuchCustomer faultInfo) {
    super(message);
    this.faultInfo = faultInfo;
  }

  /**
   * @param faultInfo
   * @param cause
   * @param message
   */
  public NoSuchCustomerException(String message, NoSuchCustomer faultInfo, Throwable cause) {
    super(message, cause);
    this.faultInfo = faultInfo;
  }

  /**
   * @return returns fault bean: com.example.customerservice.NoSuchCustomer
   */
  public NoSuchCustomer getFaultInfo() {
    return faultInfo;
  }
}
