name: Publish Documentation
on:
  push:
    branches: [ develop ]
    paths:
    - '.github/workflows/publish-documentation.yml'
    - 'docs/**'
    - 'mkdocs.yml'
    - 'CHANGELOG.md'
    - 'LICENSE'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: copy root markdown files to docs
        run: |
          cp LICENSE docs/license.md
          cp CHANGELOG.md docs/changelog.md
      - run: pip install mkdocs plantuml-markdown pymdown-extensions
      - run: mkdocs build
      - uses: actions/checkout@v2
        with:
          # disabling shallow clone, otherwise we cannot pull/push as we need to
          fetch-depth: 0
          ref: gh-pages
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          path: "apidocs"
      - name: Publish documentation
        run: |
          cd apidocs
          git rm -r * || true
          git restore --staged javadoc
          git checkout -- javadoc
          mv ../site/*  .
          git add .
          git config --global user.email "sip-dev@ikor.de"
          git config --global user.name "GitHub Actions"
          git commit -m "update documentation"
          git push
