name: Publish Documentation
on:
  push:
    branches: [ develop ]
    paths:
    - 'docs/**'
    - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: copy root markdown files to docs
        run: |
          cp README.md docs/index.md
          cp INSTALLATION.md docs/installation.md
          cp LICENSE docs/license.md
          cp CHANGELOG.md docs/changelog.md
          cp CONTRIBUTING.md docs/contributing.md
      - run: pip install mkdocs plantuml-markdown
      - run: mkdocs build
      - uses: actions/checkout@v2
        # Disabling shallow clone is recommended for improving relevancy of reporting
        with:
          fetch-depth: 0
          ref: gh-pages
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          path: "apidocs"
      - name: Publish documentation
        # todo only publish latest javadocs from main branch
        run: |
          cd apidocs
          git rm -r * || true
          git restore --staged javadoc
          git checkout -- javadoc
          mv ../site/*  .
          git add .
          git config --global user.email "sip-dev@ikor.de"
          git config --global user.name "GitHub Actions"
          git commit -m "update documentation"
          git push
